mysql:
  adapter: mysql
  database: delayed_job_test
  username: root
  encoding: utf8

mysql2:
  adapter: mysql2
  database: delayed_job_test
  username: root
  encoding: utf8
  pool: 1

postgresql:
  adapter: postgresql
  database: delayed_job_test
  username: postgres

sqlite3:
  adapter: sqlite3
  database: ":memory:"
